name: Tests - stargate-mongoose
on:
  pull_request:
  push:
jobs:
  e2e:
    runs-on: ubuntu-latest
    needs: tests
    steps:      
      - name: disable and stop mono-xsp4.service
        run: |
          sudo kill -9 $(sudo lsof -t -i:8084)
      - uses: actions/checkout@v3
      - name: Setting up the node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: setup project
        run: npm i   
      - name: benchmarks
        run: npm run benchmark