name: Tests - stargate-mongoose
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ASTRA_URI: http://localhost:8080/v1/testks1?applicationToken=d3eeb6db-8361-40dd-b9e1-2e89697376fd    
    steps:      
      - uses: actions/checkout@v3
      - name: Set up JSON API server
        run: |
          cd bin
          chmod +x start_json_api.sh
          ./start_json_api.sh
          cd ..
      - name: Wait for services
        run: |
          while ! nc -z localhost 8080; do sleep 1; done
          while ! nc -z localhost 8081; do sleep 1; done
      - name: Setting up the node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: setup project
        run: npm i
      - name: generate token given username and password
        run: |
          json_api_token=`curl -k --location 'http://localhost:8081/v1/auth' --header 'Content-Type: application/json' --data '{ "username": "cassandra", "password": "cassandra" }' | jq '.authToken'`
          echo "token: $json_api_token"
      - name: create keyspace as required
        run: |
          create_keyspace_response=`curl -k -X 'POST' 'http://localhost:8080/v1' -H 'accept: application/json' -H 'X-Cassandra-Token: $json_api_token' -H 'Content-Type: application/json' -d '{"createNamespace": {"name": "testks1"}}'`
          echo "Create keyspace response: $create_keyspace_response"