name: Tests - stargate-mongoose
on:
  pull_request:
    branches:
      - main
  push:

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      ASTRA_URI: http://localhost:8080/v1/testks1?applicationToken=d3eeb6db-8361-40dd-b9e1-2e89697376fd    
    steps:      
      - uses: actions/checkout@v3
      - name: Set up JSON API server
        run: |
          bin/start_json_api.sh
      - name: Setting up the node version
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: setup project
        run: npm i
      - name: generating token given username and password
        run: |
          echo "JSONAPI_AUTH_TOKEN=`curl -k --location 'http://localhost:8081/v1/auth' --header 'Content-Type: application/json' --data '{ \"username\": \"cassandra\", \"password\": \"cassandra\" }'`" >> $GITHUB_ENV
          echo "JSONAPI_AUTH_TOKEN : ${{ env.JSONAPI_AUTH_TOKEN }}"
