name: Tests - stargate-mongoose
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DATA_API_URI: http://localhost:8181/v1/testks1
      STARGATE_AUTH_URL: http://localhost:8081/v1/auth
      STARGATE_USERNAME: cassandra
      STARGATE_PASSWORD: cassandra
    steps:
      - uses: actions/checkout@v3
      - name: Set up Data API
        run: |
          chmod +x bin/start_data_api.sh
          bin/start_data_api.sh
      - name: Wait for services
        run: |
          while ! nc -z localhost 8181; do sleep 1; done
          while ! nc -z localhost 8081; do sleep 1; done
      - name: Setting up the node version
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - name: setup project
        run: npm i
      - name: run tests
        run: |
          npm run test
  e2e:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v3
      - name: Setting up the node version
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.0
      - name: setup project
        run: npm i
      - name: build
        run: npm run build
      - name: pack
        run: node ./bin/create-tarball.js
      - name: install smoke test
        working-directory: ./tests/e2e
        run: npm install
      - name: run e2e smoke test
        working-directory: ./tests/e2e
        run: node .
